spring:
  datasource:
    url: "jdbc:postgresql://localhost:5431/main"
    username: root
    password: password
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
      show-sql: true
      format_sql: true